project:
  output-dir: docs/
  type: website

website:
  title: "brittAnderson.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/brittAnderson
      - icon: cloud
        href: https://bsky.app/profile/britt-anderson.bsky.social
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



