#+title: Coincidence and Inductive Inference
#+date: <2023-05-15 Mon>
#+author: Britt Anderson
#+email: britt@uwaterloo.ca
#+Index: Solomonoff induction
#+Index: algorithmic probability

*** Crazy beard and crazy smart
During the pandemic, and for a term or two thereafter, I, like a lot of men, let myself grow a beard and let my hair get a bit crazy. One day when I was trying to track down a reference about something (I forget exactly what) I came across this image [[https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.wJ0Z713Zmu1ymJu7dv45IAHaKt%26pid%3DApi&f=1&ipt=65c31f7f09559cc54323f891c4c0812e607b7698085d75222ca366bd551e99a7&ipo=images][of Ray Solomonoff]] and was struck by our similar hair-dos. Who was this guy? While it was the overlapping of my interests and his work that led me to the web page where the picture appeared it was the overlap of our beard aesthetics that led me to read more about him in particular. I am so glad I did.

For awhile I have been formulating my own naive ideas about why certain events seem so much more subjectively remarkable than others even though their probabilities are essentially the same. In some cases it seems value can explain it, but certainly not all. And it also seems dependent on the knowledge of the viewer. Unsurprisingly this led me to ideas of [[https://en.wikipedia.org/wiki/Kolmogorov_complexity][Kolmogorov complexity]]  and algorithmic information theory [fn:1]. But while that formalism seemed to fit my needs it did not fit my viewpoint. Solomonoff's idea of the ideal inductive inference agent very much does. The family and friends of Solomonoff have a nice [[https://raysolomonoff.com/][website]] in his honor and with links to papers and information. I intend to expand on Solomonoff induction in another post soon. The main point for now is the interesting and wonderful discoveries that emerge when you let eclectic interests collide with the internet's extensive archive of weird and wonderful stuff. Don't let your search be too focused. Allow the interesting distractions to win out once in awhile. 



* Footnotes

[fn:1] By the way there is a great free course to get introduced to these ideas at [[https://www.edx.org/course/artificial-intelligence-algorithmic-information-aiai]]. 

