# -*- org-link-file-path-type: relative; -*-
#+Title: Britt Blog
#+email: britt@b3l.xyz
#+options: timestamp:t title:t toc:nil todo:t |:t
#+date: <2023-04-03 Mon>
#+author: Britt Anderson
#+email: britt@uwaterloo.ca
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.2 (Org mode 9.6-pre)

Welcome to yet another Britt Blog. You can find some of my academic work in the [[file:pubs.org][Publications]] section and a bit [[file:about.org][about]] me as well as some of my recent thoughts in the [[* Older Posts][Older Posts]] section below. 


#+begin_src emacs-lisp :exports none :results silent
  (load-file "./../helper-functions.el")
#+end_src

#+begin_src emacs-lisp :exports none :results silent
  (clean-and-refresh-new-posts "./posts/" 4)
#+end_src


* Recent Posts
**  Just Use Common Lisp
Date: <2023-12-08 Fri>
Author: Britt Anderson

*** Why Aren't We All Just Coding in Common Lisp?
There is history here, and I don't have the expertise to revisit it or adjudicate, but I can say that my beginner's experience with *Common Lisp* has been very favorable.

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2023-12-08-use-common-lisp.org][read full entry]] 

**  Tagging Posts with the Ox-Publish =:makeindex= Function
Date: <2023-07-20 Thu>
Author: Britt Anderson

I have been wanting to have a way to /tag/ different blog posts with different topics. This is a personal blog so the topics can ramble from fun one offs, to technical thoughts, to code snippets I want to remember. I did not see an easy way to do this until I stumbled across the =:makeindex= option for orgmode.

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2023-07-20-make-an-org-publish-index.org][read full entry]] 

**  The Genesis of Category Theory
Date: <2023-06-25 Sun>
Author: Britt Anderson

*** A creation narrative for category theory
In the beginning was chaos.

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2023-06-24-the-genesis-of-category-theory.org][read full entry]] 

**  Setting up email with gnus, mbsync, dovecot, and davmail
Date: <2023-06-15 Thu>
Author: Britt Anderson

*** The problem
My university's connect server was recently hacked, which meant that I had to leave the University's internal email system (something I had been resisting for years) for the University's preferred alternative: microsoft 365. So, now I have to reconstruct the pipeline that gets my emails from my various accounts to GNUs on my laptop.

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2023-06-15-gnus-email-and-microsoft365.org][read full entry]] 


* Older Posts
[[file:posts.org][Post List]]

* RSS
[[https://brittanderson.github.io/posts/sitemap.xml][RSS Feed]]
