# -*- org-link-file-path-type: relative; -*-
#+Title: Britt Blog
#+email: britt@b3l.xyz
#+options: timestamp:t title:t toc:nil todo:t |:t
#+date: <2023-04-03 Mon>
#+author: Britt Anderson
#+email: britt@uwaterloo.ca
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.2 (Org mode 9.6-pre)

Welcome to yet another Britt Blog. You can find some of my academic work in the [[file:pubs.org][Publications]] section and a bit [[file:about.org][about]] me as well as some of my recent thoughts in the [[* Older Posts][Older Posts]] section below. 


#+begin_src emacs-lisp :exports none :results silent
  (load-file "./../helper-functions.el")
#+end_src

#+begin_src emacs-lisp :exports none :results silent
  (clean-and-refresh-new-posts "./posts/" 3)
#+end_src


* Recent Posts
**  This is another Test
Date: <2023-04-10 Mon>
Author: Britt Anderson

Just a place holder for now, but to come is a tear stained entry of my efforts to come to terms with RSS feeds and org for blogging.

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2023-04-10-test2.org][read full entry]] 

**  This is a test
Date: <2023-04-09 Sun>
Author: Britt Anderson

Just a place holder for now, but to come is a tear stained entry of my efforts to come to terms with RSS feeds and org for blogging.

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2023-04-09-test.org][read full entry]] 

**  RSS Feeds From Org Mode and Ox-rss
Date: <2023-04-08 Sat>
Author: Britt Anderson

Just a place holder for now, but to come is a tear stained entry of my efforts to come to terms with RSS feeds and org for blogging.

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2023-04-08-rss-and-org-mode.org][read full entry]] 


* Older Posts
For a listing of all posts [[file:posts/sitemap.org][click here]].

* RSS
This [[file:sitemap.xml][link]] should work for subscribing.
