# -*- org-link-file-path-type: relative; -*-
#+Title: Britt Blog
#+email: britt@b3l.xyz
#+options: timestamp:t title:t toc:nil todo:t |:t
#+date: <2023-04-03 Mon>
#+author: Britt Anderson
#+email: britt@uwaterloo.ca
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.2 (Org mode 9.6-pre)

Welcome to yet another Britt Blog. You can find some of my academic work in the [[file:pubs.org][Publications]] section and a bit [[file:about.org][about]] me as well as some of my recent thoughts in the [[* Older Posts][Older Posts]] section below. 


#+begin_src emacs-lisp :exports none :results silent
  (load-file "./../helper-functions.el")
#+end_src

#+begin_src emacs-lisp :exports none :results silent
  (clean-and-refresh-new-posts "./posts/" 4)
#+end_src


* Recent Posts
**  Setting up email with gnus, mbsync, dovecot, and davmail
Date: <2023-06-15 Thu>
Author: Britt Anderson

* The problem
My university's connect server was recently hacked, which meant that I had to leave the University's internal email system (something I had been resisting for years) for the University's preferred alternative: microsoft 365. So, now I have to reconstruct the pipeline that gets my emails from my various accounts to GNUs on my laptop.

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2023-06-15-gnus-email-and-microsoft365.org][read full entry]] 

**  Epicurus - If it ain't wrong it is still game
Date: <2023-05-19 Fri>
Author: Britt Anderson

Most of us are familiar with [[https://en.wikipedia.org/wiki/Occam%27s_razor][Occam's Razor.]] It is a heuristic for reasoning that is often framed as the simplest explanation is the best explanation. What many of us do though is misinterpret this heuristic as suggesting that the simplest explanation is the *right* explanation. A nice by product of reading some of the literature around Solomonoff induction is to be reminded of the companion idea that any hypothesis not contradicted by experience should be retained in your set of possible answers.

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2023-05-19-epicurus.org][read full entry]] 

**  Coincidence and Inductive Inference
Date: <2023-05-15 Mon>
Author: Britt Anderson

During the pandemic, and for a term or two thereafter, I, like a lot of men, let myself grow a beard and let my hair get a bit crazy. One day when I was trying to track down a reference about something (I forget exactly what) I came across this image [[https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.wJ0Z713Zmu1ymJu7dv45IAHaKt%26pid%3DApi&f=1&ipt=65c31f7f09559cc54323f891c4c0812e607b7698085d75222ca366bd551e99a7&ipo=images][of Ray Solomonoff]] and was struck by our similar hair-dos. Who was this guy? While it was the overlapping of my interests and his work that led me to the web page where the picture appeared it was the overlap of our beard aesthetics that led me to read more about him in particular. I am so glad I did.

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2023-05-15-inductive-inference.org][read full entry]] 

**  RSS Feeds From Org Mode and Ox-rss
Date: <2023-04-08 Sat>
Author: Britt Anderson

Just a place holder for now, but to come is a tear stained entry of my efforts to come to terms with RSS feeds and org for blogging.

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2023-04-08-rss-and-org-mode.org][read full entry]] 


* Older Posts
[[file:posts.org][Post List]]

* RSS
[[https://brittanderson.github.io/posts/sitemap.xml][RSS Feed]]
