# -*- org-link-file-path-type: relative; -*-
#+Title: Britt Blog
#+email: britt@b3l.xyz
#+options: timestamp:t title:t toc:nil todo:t |:t
#+date: <2023-04-03 Mon>
#+author: Britt Anderson
#+email: britt@uwaterloo.ca
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.2 (Org mode 9.6-pre)

Welcome to yet another Britt Blog. You can find some of my academic work in the [[file:pubs.org][Publications]] section and a bit [[file:about.org][about]] me as well as some of my recent thoughts in the [[* Older Posts][Older Posts]] section below. 


#+begin_src emacs-lisp :exports none :results silent
  (load-file "./../helper-functions.el")
#+end_src

#+begin_src emacs-lisp :exports none :results silent
  (clean-and-refresh-new-posts "./posts/" 3)
#+end_src


* Recent Posts
**  Coincidence and Inductive Inference
Date: <2023-05-15 Mon>
Author: Britt Anderson

During the pandemic, and for a term or two thereafter, I, like a lot of men, let myself grow a beard and let my hair get a bit crazy. One day when I was trying to track down a reference about something (I forget exactly what) I came across this image [[https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.wJ0Z713Zmu1ymJu7dv45IAHaKt%26pid%3DApi&f=1&ipt=65c31f7f09559cc54323f891c4c0812e607b7698085d75222ca366bd551e99a7&ipo=images][of Ray Solomonoff]] and was struck by our similar hair-dos. Who was this guy? While it was the overlapping of my interests and his work that led me to the web page where the picture appeared it was the overlap of our beard aesthetics that led me to read more about him in particular. I am so glad I did.

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2023-05-15-inductive-inference.org][read full entry]] 

**  RSS Feeds From Org Mode and Ox-rss
Date: <2023-04-08 Sat>
Author: Britt Anderson

Just a place holder for now, but to come is a tear stained entry of my efforts to come to terms with RSS feeds and org for blogging.

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2023-04-08-rss-and-org-mode.org][read full entry]] 

**  Publish Your Embarassing Code
Date: <2023-04-03 Mon>
Author: Britt Anderson

I am a long term Emacs user, and I love it, but while I am quick to adopt new packages (and frequently break my ~init.el~) I have never fully exploited the fact that Emacs is programmable. The pitch I am making here is to publish your embarassing code so that you help give courage to others to try. You do this by debunking the myth that everyone else is an Uber-coder, and by giving more beginner friendly examples to help people get a leg up.

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2023-04-03-writing-emacs-lisp.org][read full entry]] 


* Older Posts
For a listing of all posts [[file:posts/sitemap.org][click here]].

* RSS
This [[file:sitemap.xml][link]] should work for subscribing.
