# -*- org-link-file-path-type: relative; -*-
#+Title: Britt Blog
#+email: britt@b3l.xyz
#+options: timestamp:t title:t toc:nil todo:t |:t
#+date: <2024-01-22 Mon>
#+author: Britt Anderson
#+email: britt@uwaterloo.ca
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.2 (Org mode 9.6-pre)

Welcome to yet another Britt Blog. You can find some of my academic work in the [[file:pubs.org][Publications]] section and a bit [[file:about.org][about]] me as well as some of my recent thoughts in the [[* Older Posts][Older Posts]] section below. 


#+begin_src emacs-lisp :exports none :results silent
  (load-file "./../helper-functions.el")
#+end_src

#+begin_src emacs-lisp :exports none :results silent
  (clean-and-refresh-new-posts "./posts/" 4)
#+end_src


* Recent Posts
**  Lean 4, Emacs, and Archlinux
Date: <2024-08-22 Thu>
Author: Britt Anderson

*** Formalizing Cognitive Science
This is the clear goal. The path remains murky. But, inspired by the recent [[https://www.youtube.com/live/ZOT5jQ8W2Nc?feature=shared][Topos Institute Colloquium by Will Crichton]], I decided to download [[https://lean-lang.org/download/][Lean]] to my computer to see if I could begin to explore it as yet another tool I will only use intermittently, if at all, in my pursuit of the "clear goal" via the process of iterative preparation.

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2024-08-22-lean-emacs-and-archlinux.org][read full entry]] 

**  Haskell, Eglot, Language Servers, and Emacs
Date: <2024-04-19 Fri>
Author: Britt Anderson

*** Haskell Coding in Emacs
Haskell is a programming language where the rate of development and the evolution of its tooling can make it challenging to love. But love it I do, even though in many ways it is the antithesis of Common Lisp. If the latter is a /forever language/ it sometimes feels as if Haskell is a /never language/, because I spend so much time trying to figure out how to get it working (admittedly I am only an intermittent user) that by the time I am done, I never write any code.

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2024-04-19-haskell-emacs.org][read full entry]] 

**  Use ~fdm~ to make your emacs-org-mode email workflow smoother
Date: <2024-01-22 Mon>
Author: Britt Anderson

*** FDM: a tool to make an emacs email workflow smoother

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2024-01-22-fdm-for-routing-mail.org][read full entry]] 

**  Just Use Common Lisp
Date: <2023-12-08 Fri>
Author: Britt Anderson

*** Why Aren't We All Just Coding in Common Lisp?
There is history here, and I don't have the expertise to revisit it or adjudicate, but I can say that my beginner's experience with *Common Lisp* has been very favorable.

[[/home/britt/gitRepos/brittAnderson.github.io/raw/posts/2023-12-08-use-common-lisp.org][read full entry]] 


* Older Posts
[[file:posts.org][Post List]]

* RSS
[[https://brittanderson.github.io/posts/sitemap.xml][RSS Feed]]
