# -*- org-link-file-path-type: relative; -*-
#+Title: Britt Blog
#+email: britt@b3l.xyz
#+options: timestamp:t title:t toc:nil todo:t |:t
#+date:
#+author: Britt Anderson
#+email: britt@uwaterloo.ca
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.2 (Org mode 9.6-pre)

Welcome to yet another Britt Blog. You can find some of my academic work in the [[file:pubs.org][Publications]] section and a bit [[file:about.org][about]] me as well as some of my recent thoughts in the Posts section [[ref:posts][below]].
(erase-recent-posts)

#+begin_src emacs-lisp :exports none :results silent
  (load-file "./../helper-functions.el")
#+end_src

#+begin_src emacs-lisp :exports none :results silent
  (clean-and-refresh-new-posts "./posts/" 1)
#+end_src


* Recent Posts
**  Back to Org Mode
Date: <2023-01-09 Mon>
Author: Britt Anderson

For sometime now my [[https://brittlab.uwaterloo.ca][laboratory website]] has been in Jekyll.
This was a really nice solution in the beginning.
The look was clean, everyone in the lab could update their own content, and new members could learn to use a mark-up language to write posts.
However, Jekyll and the Ruby engine that powers it have gotten a bit harder to use over the years, and now everytime I want to update the lab webpage I have to figure out how to update all my gems, and various other housekeeping procedures just to write a blog post or remind myself how to create an internal link.
I wanted to simplify again and use something that I would not have to constantly re-educate myself how to use.

[[/home/britt/gitRepos/brittOrgSite/raw/posts/2023-01-09-back-to-org-mode.org][read full entry]] 


* Older Posts
label:posts
For a listing of all posts [[./posts/sitemap.org][click here]].
