---
title: What is Attention Redux
author: Britt Anderson
tags: raisin
---

* What is Attention

  In 2011 I published an [[https://www.frontiersin.org/articles/10.3389/fpsyg.2011.00246/full][article]] called "There is no such thing as attention." This year I wrote a submission that I hope will appear in [[https://onlinelibrary.wiley.com/journal/19395086#?tabActivePane=][WIREs Cognitive Science]] revisiting this issues; this time as an opinion piece for a collection to be titled /What is Attention?/

  
* There /still/ is no such thing as attention.

  Basically, my answer to the question is the same: What is attention? Nothing *is* attention. But my purpose here is to reflect a bit on coming back to a topic ten years later and how I perceive the changing landscape.

  I feel a lot less fervor for the issue. My opinion is as deeply held, and I feel the evidence is greater than before. What has changed is my general sense that the battle is won. Not because I wrote my article. My article did not direct the /zeitgeist/ it reflected it. I have gotten a lot of feedback on that article. Some people cite me, but I have the sense that many more read it and liked it then ever quote it or cite it. I think that is because I gave voice to something that many people felt and that more people now feel. The word attention is not fit for purpose. It has a certain practical benefit of helping you find the posters that will interest you at a conference, but it doesn't help you organize your data, conceive your experiments, or appear as a useful construct in your theories. 

* Attention as Exemplar

  I gave words to some ideas that I didn't invent, but simply detected. And one of the reasons I feel my piece got some attention was because others recognized their feelings and suspicions in my words, and it gave them a concrete signpost to point to when wanting to share their concerns with others.

  Well and good, but then why write again on the same topic if my opinion is largely the same and the consensus seems to be converging to the same position? There is probably an argument to be made for writing the same paper over and over as a tactic to achieve recognition in academics. I won't deny the argument in general, but it doen't appeal to me. I have enough trouble finding the personal capital to invest in writing articles the first time. Once I know what I want to say, and how I intend to say it; a stage that occurs fairly early in the writing process, my own personal goals are largely met, and I have to rely on my stubborness to finish /actually/ writing the article, and not just living with my mentalized version. I accept the professional benefits of repeating your story over and over, but that wasn't what got me to bother revisiting the question of what is attention. It is that attention seems to be a very good example of a more general problem. One that plagues psychology in particular: conceptual fragmentation. Understanding what that is can help us in science a lot. It can help us recognize terms we should eliminate from our discourse and arguments where we might think we are arguing about a shared concept, but in fact have been tricked by subtle distinctions into wasting our time and ink comparing apples and oranges. There are heuristic guidelines for recognizing these futile debates and suspect terms. I found the impetus to revisit the issue of attention, because it gave me the opportunity to read and think about the topic of conceptual fragmentation generally, and discourse eliminativism: where we agree to remove a word from our scientific conversations. Another article on "What is Attention?" allowed me to share this new enthusiam. That is the moral. To find the motivation to revisit an old, at least for you, topic find the new angle or the new application.

  
* Please read ...

  I would like to advertise the article by [[https://link.springer.com/article/10.1007/s13194-016-0136-2][Taylor and Vickers]]. It is a very readable overview of this topic that will benefit you regardless of your interest in the debate over attention. And they did cite me after all. 
